### ISSUE TITLE
Campos requeridos

### ISSUE THREAD

**Issue by mara9303** [JeanCarlosChavarriaHughes/API_Hacienda#21]
Revisar todos los campos solicitados por hacienda según el documento de anexos y estructuras y validar los que sean requeridos en sus direfentes documentos FE, NC, ND, TE
ANEXOS Y ESTRUCTURAS
https://www.hacienda.go.cr/ATV/ComprobanteElectronico/docs/esquemas/2016/v4.3/ANEXOS%20Y%20ESTRUCTURAS_V4.3.pdf

**Comment by JeanCarlosChavarriaHughes** [comment]
@mara9303 
1. Validar que el campo TipoDoc, en informacion Referencia es de 2 dígitos.
2. Validar que el codigo, en informacion Referencia es de 2 dígitos.

element TipoDoc: Schemas validity error :
- Element '{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronica}TipoDoc': [facet 'enumeration'] The value '1' is not an element of the set {'01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '13', '99'}.
element TipoDoc: Schemas validity error :
- Element '{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronica}TipoDoc': '1' is not a valid value of the local atomic type.



element Codigo: Schemas validity error :
- Element '{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronica}Codigo': [facet 'enumeration'] The value '1' is not an element of the set {'01', '02', '03', '04', '05', '99'}.
element Codigo: Schemas validity error :
- Element '{https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronica}Codigo': '1' is not a valid value of the local atomic type.

**Comment by JeanCarlosChavarriaHughes** [comment]
@mara9303  Voy a cerrar este issue ya que está resuelto. Voy a abrir otro para actualizar la documentación. Me parece que con respecto a los objetivos de actualizar Factura Electronica, Notas de Debito, Crédito y Tiquetes está finalizado.
