### ISSUE TITLE
Actualizar los Headers

### ISSUE THREAD

**Issue by JeanCarlosChavarriaHughes** [JeanCarlosChavarriaHughes/API_Hacienda#32]
**Description**
Cada documento generado y enviado a hacienda en api-staging es rechazado. Una posible razón del rechazo son los headers.

**Pasos para reproducir**
1. Generar un XML.
2. Firmar el XML.
3. Enviar el XML a Hacienda
4. Consultar la recepción del XML con GET. Ejemplo:
https://api.comprobanteselectronicos.go.cr/recepcion-sandbox/v1/recepcion/50611091900012548763200100001010000000058184619703
Con el Authorization bearer <token>

Actual
Los Headers usados en genxml son:
    ```<FacturaElectronica
    xmlns="https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronica"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        <Clave>' . $clave . '</Clave>```

Probar:
Probar si con los siguientes Headers, se puede validar la recepción del documento:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?><FacturaElectronica xmlns="https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.3/facturaElectronica">
```
Cambiando facturaElectronica, tiqueteElectronico, notaDebito, notaCredito, mensajeReceptor segun corresponda.

**Comment by jairo0920** [comment]
Hola, todo bien.! Vieras que estaba probando tu codigo pero en el momento que realizo la firma del XML con el modulo "firmarXML", no me devuelve nada "Operation timed out after 30001 milliseconds with 0 bytes received", lo realizo con el modulo "signXML" pero me rechaza el TE, me indica este error: "Error al comunicarse con el Signum One"

**Comment by JeanCarlosChavarriaHughes** [comment]
Hola, el endpoint de firmarxml solo se copió y pegó del módulo original de enzo:
https://github.com/enzojimenez/hacienda-firmador-php

puede confirmar que estás siguiendo los argumentos, es extraño a mí me funciona.

**Comment by JeanCarlosChavarriaHughes** [comment]
<img width="599" alt="Screen Shot 2019-09-18 at 11 01 40 PM" src="https://user-images.githubusercontent.com/8434928/65214881-ce0e2c00-da68-11e9-8c07-81bc88784f40.png">

**Comment by JeanCarlosChavarriaHughes** [comment]
@jairo0920
