### ISSUE TITLE
[API Upgrade] [Otros]

### ISSUE THREAD

**Issue by JeanCarlosChavarriaHughes** [JeanCarlosChavarriaHughes/API_Hacienda#9]
# Otros
comprende la información requerida para las relaciones de comercio electrónico entre las partes que no contravenga lo establecido en la presente resolución.

# Fuente
Este es el formato limpio del XSD para 4.3 en FE
https://www.hacienda.go.cr/ATV/ComprobanteElectronico/docs/esquemas/2016/v4.3/FacturaElectronica_V4.3.xsd

## Nueva definition de Anexos y Estructuras
https://www.hacienda.go.cr/ATV/ComprobanteElectronico/docs/esquemas/2016/v4.3/ANEXOS%20Y%20ESTRUCTURAS_V4.3.pdf

## Nueva Resolution
https://www.hacienda.go.cr/ATV/ComprobanteElectronico/docs/esquemas/2016/v4.3/ResolucionComprobantesElectronicosDGT-R-48-2016_4.3.pdf

## Otros comprobantes
https://www.hacienda.go.cr/ATV/ComprobanteElectronico/frmAnexosyEstructuras.aspx#

**Comment by JeanCarlosChavarriaHughes** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(5) API Upgrade -Otros](https://trello.com/c/KsEcNmuw/52-5-api-upgrade-otros)

**Comment by mara9303** [comment]
Según la resolución el api recibe los campos correctamente, adjunto curl post y RESPONSE
POST:
curl -X POST \
  'http://localhost/www/api.php?w=genXML&r=gen_xml_fe&clave=50610061900310262197200100001010000001334180731959&consecutivo=00100001010000001334&fecha_emision=2019-06-10T10%3A42%3A43-06%3A00&emisor_nombre=Sistemas%20Inteligente%20SRL&emisor_tipo_indetif=02&emisor_num_identif=3102621972&nombre_comercial=Sistemas%20Inteligente%20SRL&emisor_provincia=1&emisor_canton=13&emisor_distrito=05&emisor_barrio=02&emisor_otras_senas=Detras%20del%20Walmart&emisor_cod_pais_tel=506&emisor_tel=84545845&emisor_email=michael%40pruebas.cr&receptor_nombre=Bryan%20Navarro&receptor_tipo_identif=01&receptor_num_identif=305460345&receptor_cod_pais_tel=506&receptor_tel=24758957&receptor_email=bnavarro%40pruebas.cr1&condicion_venta=02&plazo_credito=1%20d%C3%ADas&medio_pago=04&cod_moneda=USD&tipo_cambio=588.66&total_serv_gravados=0&total_serv_exentos=9497.00000&total_merc_gravada=0&total_merc_exenta=0&total_gravados=0&total_exento=9497.00000&total_ventas=9497.00000&total_descuentos=0&total_ventas_neta=9497.00000&total_impuestos=0&total_comprobante=9497.00000&codigo_actividad=70200&total_serv_exonerados=9497.00000&total_merc_exonerada=0&total_exonerado=9497.00000&totalIVADevuelto=0&totalOtrosCargos=0&infoRefeTipoDoc=1&infoRefeNumero=2&infoRefeFechaEmision=4&infoRefeCodigo=1&infoRefeRazon=Calidad&detalles=%5B%0A%20%20%7B%0A%20%20%20%20%22cantidad%22%3A%201%2C%0A%20%20%20%20%22unidadMedida%22%3A%20%22Sp%22%2C%0A%20%20%20%20%22detalle%22%3A%20%22Multa%20por%20Morosidad%20%2F%20febrero%202019%2C%20Filial%20FF02%22%2C%0A%20%20%20%20%22precioUnitario%22%3A%209497%2C%0A%20%20%20%20%22montoTotal%22%3A%209497%2C%0A%20%20%20%20%22subtotal%22%3A%209497%2C%0A%20%20%20%20%22montoTotalLinea%22%3A%209497%2C%0A%20%20%20%20%22unidadMedidaComercial%22%3A%20%221%20Multa%22%2C%0A%20%20%20%20%22codigo%22%3A%20%22%22%2C%0A%20%20%20%20%22baseImponible%22%3A%20%22%22%2C%0A%20%20%20%20%22impuestoNeto%22%3A%200%2C%0A%20%20%20%20%22codigoComercial%22%3A%20%5B%0A%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22codigo%22%3A%20%2204%22%2C%0A%20%20%20%20%20%20%20%20%22tipo%22%3A%20%22MICROSOFT%22%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%5D%2C%0A%20%20%20%20%22descuento%22%3A%20%5B%0A%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22montoDescuento%22%3A%200%2C%0A%20%20%20%20%20%20%20%20%22naturalezaDescuento%22%3A%200%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%5D%2C%0A%20%20%20%20%22impuesto%22%3A%20%5B%0A%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22codigo%22%3A%20%2201%22%2C%0A%20%20%20%20%20%20%20%20%22monto%22%3A%200%2C%0A%20%20%20%20%20%20%20%20%22codigoTarifa%22%3A%20%2201%22%2C%0A%20%20%20%20%20%20%20%20%22tarifa%22%3A%200%2C%0A%20%20%20%20%20%20%20%20%22factorIVA%22%3A%200%2C%0A%20%20%20%20%20%20%20%20%22montoExportacion%22%3A%200%2C%0A%20%20%20%20%20%20%20%20%22exoneracion%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%22tipoDocumento%22%3A%20%2201%22%2C%0A%20%20%20%20%20%20%20%20%20%20%22numeroDocumento%22%3A%20%22BA3-21444-03%22%2C%0A%20%20%20%20%20%20%20%20%20%20%22nombreInstitucion%22%3A%20%22Ba3%20Software%20Corporation%22%2C%0A%20%20%20%20%20%20%20%20%20%20%22fechaEmision%22%3A%20%222018-10-10T09%3A00%3A00-06%3A00%22%2C%0A%20%20%20%20%20%20%20%20%20%20%22montoExoneracion%22%3A%200%2C%0A%20%20%20%20%20%20%20%20%20%20%22porcentajeExoneracion%22%3A%201%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%5D%0A%20%20%7D%0A%5D&otros=PRUEBA%20DE%20OTRO%20TEXTO&otrosType=OtroTexto' \
  -H 'cache-control: no-cache' \
  -H 'postman-token: 37fc7ff9-047a-5276-29c6-0582ff674901'

RESPONSE:
{
    "resp": {
        "clave": "50610061900310262197200100001010000001334180731959",
        "xml": "PD94bWwgdmVyc2lvbiA9ICIxLjAiIGVuY29kaW5nID0gInV0Zi04Ij8+DQogICAgPEZhY3R1cmFFbGVjdHJvbmljYQ0KICAgIHhtbG5zPSJodHRwczovL2Nkbi5jb21wcm9iYW50ZXNlbGVjdHJvbmljb3MuZ28uY3IveG1sLXNjaGVtYXMvdjQuMy9mYWN0dXJhRWxlY3Ryb25pY2EiDQogICAgeG1sbnM6eHNkPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSINCiAgICB4bWxuczp4c2k9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hLWluc3RhbmNlIj4NCiAgICAgICAgPENsYXZlPjUwNjEwMDYxOTAwMzEwMjYyMTk3MjAwMTAwMDAxMDEwMDAwMDAxMzM0MTgwNzMxOTU5PC9DbGF2ZT4NCiAgICAgICAgPENvZGlnb0FjdGl2aWRhZD43MDIwMDwvQ29kaWdvQWN0aXZpZGFkPg0KICAgICAgICA8TnVtZXJvQ29uc2VjdXRpdm8+MDAxMDAwMDEwMTAwMDAwMDEzMzQ8L051bWVyb0NvbnNlY3V0aXZvPg0KICAgICAgICA8RmVjaGFFbWlzaW9uPjIwMTktMDYtMTBUMTA6NDI6NDMtMDY6MDA8L0ZlY2hhRW1pc2lvbj4NCiAgICAgICAgPEVtaXNvcj4NCiAgICAgICAgICAgIDxOb21icmU+U2lzdGVtYXMgSW50ZWxpZ2VudGUgU1JMPC9Ob21icmU+DQogICAgICAgICAgICA8SWRlbnRpZmljYWNpb24+DQogICAgICAgICAgICAgICAgPFRpcG8+MDI8L1RpcG8+DQogICAgICAgICAgICAgICAgPE51bWVybz4zMTAyNjIxOTcyPC9OdW1lcm8+DQogICAgICAgICAgICA8L0lkZW50aWZpY2FjaW9uPg0KICAgICAgICAgICAgPE5vbWJyZUNvbWVyY2lhbD5TaXN0ZW1hcyBJbnRlbGlnZW50ZSBTUkw8L05vbWJyZUNvbWVyY2lhbD4NCiAgICAgICAgPFViaWNhY2lvbj4NCiAgICAgICAgICAgIDxQcm92aW5jaWE+MTwvUHJvdmluY2lhPg0KICAgICAgICAgICAgPENhbnRvbj4xMzwvQ2FudG9uPg0KICAgICAgICAgICAgPERpc3RyaXRvPjA1PC9EaXN0cml0bz48QmFycmlvPjAyPC9CYXJyaW8+DQogICAgICAgICAgICAgICAgPE90cmFzU2VuYXM+RGV0cmFzIGRlbCBXYWxtYXJ0PC9PdHJhc1NlbmFzPg0KICAgICAgICAgICAgPC9VYmljYWNpb24+DQogICAgICAgICAgICA8VGVsZWZvbm8+DQogICAgICAgICAgICAgICAgPENvZGlnb1BhaXM+NTA2PC9Db2RpZ29QYWlzPg0KICAgICAgICAgICAgICAgIDxOdW1UZWxlZm9ubz44NDU0NTg0NTwvTnVtVGVsZWZvbm8+DQogICAgICAgICAgICA8L1RlbGVmb25vPjxDb3JyZW9FbGVjdHJvbmljbz5taWNoYWVsQHBydWViYXMuY3I8L0NvcnJlb0VsZWN0cm9uaWNvPg0KICAgICAgICA8L0VtaXNvcj48UmVjZXB0b3I+DQogICAgICAgICAgICA8Tm9tYnJlPkJyeWFuIE5hdmFycm88L05vbWJyZT48SWRlbnRpZmljYWNpb24+DQogICAgICAgICAgICAgICAgICAgIDxUaXBvPjAxPC9UaXBvPg0KICAgICAgICAgICAgICAgICAgICA8TnVtZXJvPjMwNTQ2MDM0NTwvTnVtZXJvPg0KICAgICAgICAgICAgICAgIDwvSWRlbnRpZmljYWNpb24+PFRlbGVmb25vPg0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPENvZGlnb1BhaXM+NTA2PC9Db2RpZ29QYWlzPg0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPE51bVRlbGVmb25vPjI0NzU4OTU3PC9OdW1UZWxlZm9ubz4NCiAgICAgICAgICAgICAgICAgICAgPC9UZWxlZm9ubz48Q29ycmVvRWxlY3Ryb25pY28+Ym5hdmFycm9AcHJ1ZWJhcy5jcjE8L0NvcnJlb0VsZWN0cm9uaWNvPjwvUmVjZXB0b3I+DQogICAgICAgIDxDb25kaWNpb25WZW50YT4wMjwvQ29uZGljaW9uVmVudGE+DQogICAgICAgIDxQbGF6b0NyZWRpdG8+MSBkw61hczwvUGxhem9DcmVkaXRvPg0KICAgICAgICA8TWVkaW9QYWdvPjA0PC9NZWRpb1BhZ28+DQogICAgICAgIDxEZXRhbGxlU2VydmljaW8+PExpbmVhRGV0YWxsZT4NCiAgICAgICAgICAgICAgICAgIDxOdW1lcm9MaW5lYT4xPC9OdW1lcm9MaW5lYT4NCiAgICAgICAgICAgICAgICAgIDxDYW50aWRhZD4xPC9DYW50aWRhZD4NCiAgICAgICAgICAgICAgICAgIDxVbmlkYWRNZWRpZGE+U3A8L1VuaWRhZE1lZGlkYT4NCiAgICAgICAgICAgICAgICAgIDxEZXRhbGxlPk11bHRhIHBvciBNb3Jvc2lkYWQgLyBmZWJyZXJvIDIwMTksIEZpbGlhbCBGRjAyPC9EZXRhbGxlPg0KICAgICAgICAgICAgICAgICAgPFByZWNpb1VuaXRhcmlvPjk0OTc8L1ByZWNpb1VuaXRhcmlvPg0KICAgICAgICAgICAgICAgICAgPE1vbnRvVG90YWw+OTQ5NzwvTW9udG9Ub3RhbD48U3ViVG90YWw+OTQ5NzwvU3ViVG90YWw+PEltcHVlc3RvPg0KICAgICAgICAgICAgICAgIDxDb2RpZ28+MDE8L0NvZGlnbz4NCiAgICAgICAgICAgICAgICA8VGFyaWZhPjA8L1RhcmlmYT4NCiAgICAgICAgICAgICAgICA8TW9udG8+MDwvTW9udG8+DQogICAgICAgICAgICAgICAgICAgIDxFeG9uZXJhY2lvbj4NCiAgICAgICAgICAgICAgICAgICAgICAgIDxUaXBvRG9jdW1lbnRvPjAxPC9UaXBvRG9jdW1lbnRvPg0KICAgICAgICAgICAgICAgICAgICAgICAgPE51bWVyb0RvY3VtZW50bz5CQTMtMjE0NDQtMDM8L051bWVyb0RvY3VtZW50bz4NCiAgICAgICAgICAgICAgICAgICAgICAgIDxOb21icmVJbnN0aXR1Y2lvbj5CYTMgU29mdHdhcmUgQ29ycG9yYXRpb248L05vbWJyZUluc3RpdHVjaW9uPg0KICAgICAgICAgICAgICAgICAgICAgICAgPEZlY2hhRW1pc2lvbj4yMDE4LTEwLTEwVDA5OjAwOjAwLTA2OjAwPC9GZWNoYUVtaXNpb24+DQogICAgICAgICAgICAgICAgICAgICAgICA8TW9udG9JbXB1ZXN0bz48L01vbnRvSW1wdWVzdG8+DQogICAgICAgICAgICAgICAgICAgICAgICA8UG9yY2VudGFqZUNvbXByYT48L1BvcmNlbnRhamVDb21wcmE+DQogICAgICAgICAgICAgICAgICAgIDwvRXhvbmVyYWNpb24+PC9JbXB1ZXN0bz48TW9udG9Ub3RhbExpbmVhPjk0OTc8L01vbnRvVG90YWxMaW5lYT48L0xpbmVhRGV0YWxsZT48L0RldGFsbGVTZXJ2aWNpbz4NCiAgICAgICAgPFJlc3VtZW5GYWN0dXJhPg0KICAgICAgICA8Q29kaWdvVGlwb01vbmVkYT4NCiAgICAgICAgICAgIDxDb2RpZ29Nb25lZGE+VVNEPC9Db2RpZ29Nb25lZGE+DQogICAgICAgICAgICA8VGlwb0NhbWJpbz41ODguNjY8L1RpcG9DYW1iaW8+DQogICAgICAgIDwvQ29kaWdvVGlwb01vbmVkYT4NCiAgICAgICAgPFRvdGFsU2VydkdyYXZhZG9zPjA8L1RvdGFsU2VydkdyYXZhZG9zPg0KICAgICAgICA8VG90YWxTZXJ2RXhlbnRvcz45NDk3LjAwMDAwPC9Ub3RhbFNlcnZFeGVudG9zPg0KICAgICAgICA8VG90YWxTZXJ2RXhvbmVyYWRvPjk0OTcuMDAwMDA8L1RvdGFsU2VydkV4b25lcmFkbz4NCiAgICAgICAgPFRvdGFsTWVyY2FuY2lhc0dyYXZhZGFzPjA8L1RvdGFsTWVyY2FuY2lhc0dyYXZhZGFzPg0KICAgICAgICA8VG90YWxNZXJjYW5jaWFzRXhlbnRhcz4wPC9Ub3RhbE1lcmNhbmNpYXNFeGVudGFzPg0KICAgICAgICA8VG90YWxNZXJjRXhvbmVyYWRhPjA8L1RvdGFsTWVyY0V4b25lcmFkYT4NCiAgICAgICAgPFRvdGFsR3JhdmFkbz4wPC9Ub3RhbEdyYXZhZG8+DQogICAgICAgIDxUb3RhbEV4ZW50bz45NDk3LjAwMDAwPC9Ub3RhbEV4ZW50bz4NCiAgICAgICAgPFRvdGFsRXhvbmVyYWRvPjk0OTcuMDAwMDA8L1RvdGFsRXhvbmVyYWRvPg0KICAgICAgICA8VG90YWxWZW50YT45NDk3LjAwMDAwPC9Ub3RhbFZlbnRhPg0KICAgICAgICA8VG90YWxEZXNjdWVudG9zPjA8L1RvdGFsRGVzY3VlbnRvcz4NCiAgICAgICAgPFRvdGFsVmVudGFOZXRhPjk0OTcuMDAwMDA8L1RvdGFsVmVudGFOZXRhPg0KICAgICAgICA8VG90YWxJbXB1ZXN0bz4wPC9Ub3RhbEltcHVlc3RvPg0KICAgICAgICA8VG90YWxJVkFEZXZ1ZWx0bz4wPC9Ub3RhbElWQURldnVlbHRvPg0KICAgICAgICA8VG90YWxPdHJvc0Nhcmdvcz4wPC9Ub3RhbE90cm9zQ2FyZ29zPg0KICAgICAgICA8VG90YWxDb21wcm9iYW50ZT45NDk3LjAwMDAwPC9Ub3RhbENvbXByb2JhbnRlPg0KICAgICAgICA8L1Jlc3VtZW5GYWN0dXJhPg0KICAgICAgICA8Tm9ybWF0aXZhPg0KICAgICAgICA8TnVtZXJvUmVzb2x1Y2lvbj5ER1QtUi00OC0yMDE2PC9OdW1lcm9SZXNvbHVjaW9uPg0KICAgICAgICA8RmVjaGFSZXNvbHVjaW9uPjA3LTEwLTIwMTYgMDg6MDA6MDA8L0ZlY2hhUmVzb2x1Y2lvbj4NCiAgICAgICAgPC9Ob3JtYXRpdmE+PEluZm9ybWFjaW9uUmVmZXJlbmNpYT4NCiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8VGlwb0RvYz4xPC9UaXBvRG9jPg0KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxOdW1lcm8+MjwvTnVtZXJvPg0KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxGZWNoYUVtaXNpb24+NDwvRmVjaGFFbWlzaW9uPg0KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxDb2RpZ28+MTwvQ29kaWdvPg0KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxSYXpvbj5DYWxpZGFkPC9SYXpvbj4NCiAgICAgICAgICAgICAgICAgICAgICAgIDwvSW5mb3JtYWNpb25SZWZlcmVuY2lhPg0KICAgICAgICAgICAgICAgIDxPdHJvcz4NCiAgICAgICAgICAgIDxPdHJvVGV4dG8+UFJVRUJBIERFIE9UUk8gVEVYVE88L090cm9UZXh0bz4NCiAgICAgICAgICAgIDwvT3Ryb3M+DQogICAgPC9GYWN0dXJhRWxlY3Ryb25pY2E+"
    }
}
